bf16: true
cutoff_len: 50000
dataset: dafny_train113_alpaca
dataset_dir: data
ddp_timeout: 180000000
do_train: true
finetuning_type: full
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: huggyllama/llama-7b
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Llama-7B/full/train_2024-11-05-11-01-09
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: default
warmup_steps: 0
