bf16: true
cutoff_len: 50000
dataset: identity,alpaca_en_demo
dataset_dir: data
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: llava-hf/llama3-llava-next-8b-hf
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/LLaVA-NeXT-Llama3-8B-Chat/lora/train_2024-11-05-11-01-09
packing: false
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: llava_next_llama3
warmup_steps: 0
